name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js '20.12.2'
      uses: actions/setup-node@v4
      with:
        node-version: "20.12.2"
        cache: "npm"
    - id: Build-Vue
      uses: SerhiiKa/VuePagesAction@1.0.4
      with:
        username: 'AlinaAkimova'
        reponame: 'invitation'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
